//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUASCYCLAB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class IncomeStatement
    {
        [Key]
        [Display(Name = "損益表編號")]
        public System.Guid IncomeStatementID { get; set; }
        [Display(Name = "統計年度")]
        public string AnnualStatistics { get; set; }
        [Display(Name = "稅前淨利")]
        public string PreTaxIncome { get; set; }
        [Display(Name = "稅後淨利")]
        public string NetIncome { get; set; }
        [Display(Name = "會計負責人姓名")]
        public string AccountingDepartmentEmployee { get; set; }
        public System.Guid SalesIncomeRecordID { get; set; }
        public System.Guid PurchaseRequestPaymentID { get; set; }
        public System.Guid PurchaseInvoiceID { get; set; }
        public System.Guid SalesInvoiceID { get; set; }
        public System.Guid InventoryRecordID { get; set; }
        public System.Guid MaterialInventoryRecordID { get; set; }

        public virtual InventoryRecord InventoryRecord { get; set; }
        public virtual MaterialInventoryRecord MaterialInventoryRecord { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice1 { get; set; }
        public virtual PurchaseRequestPayment PurchaseRequestPayment { get; set; }
        public virtual SalesIncomeRecord SalesIncomeRecord { get; set; }
        public virtual SalesInvoice_ SalesInvoice_ { get; set; }
    }
}
