//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUASCYCLAB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class InventoryReceipt
    {
        public InventoryReceipt()
        {
            this.InventoryRecords = new HashSet<InventoryRecord>();
        }
        [Key]
        [Display(Name = "盤點單編號")]
        public System.Guid InventoryReceiptID { get; set; }
        [Display(Name = "生產負責人姓名")]
        public string ProductionInChargeOfName { get; set; }
        [Display(Name = "倉管負責人姓名")]
        public string WarehouseResponsibleName { get; set; }
        [Display(Name = "盤點日")]
        public System.DateTime InventoryDate { get; set; }
        public System.Guid ProductionOrderID { get; set; }

        public virtual ProductionOrder ProductionOrder { get; set; }
        public virtual ICollection<InventoryRecord> InventoryRecords { get; set; }
    }
}
