//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUASCYCLAB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KUASCYCEntities : DbContext
    {
        public KUASCYCEntities()
            : base("name=KUASCYCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOMList> BOMLists { get; set; }
        public virtual DbSet<CustomerProfile> CustomerProfiles { get; set; }
        public virtual DbSet<IncomeStatement> IncomeStatements { get; set; }
        public virtual DbSet<Inquiry> Inquiries { get; set; }
        public virtual DbSet<InventoryReceipt> InventoryReceipts { get; set; }
        public virtual DbSet<InventoryRecord> InventoryRecords { get; set; }
        public virtual DbSet<MaterialInventoryRecord> MaterialInventoryRecords { get; set; }
        public virtual DbSet<PackingList> PackingLists { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductionOrder> ProductionOrders { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual DbSet<PurchaseRequestPayment> PurchaseRequestPayments { get; set; }
        public virtual DbSet<PurchaseRequisition> PurchaseRequisitions { get; set; }
        public virtual DbSet<PurchaseReturn> PurchaseReturns { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<SalesChart> SalesCharts { get; set; }
        public virtual DbSet<SalesIncome> SalesIncomes { get; set; }
        public virtual DbSet<SalesIncomeRecord> SalesIncomeRecords { get; set; }
        public virtual DbSet<SalesInvoice_> SalesInvoice_ { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
        public virtual DbSet<SalesRequestPayment> SalesRequestPayments { get; set; }
        public virtual DbSet<SalesRequestPaymentRecord> SalesRequestPaymentRecords { get; set; }
        public virtual DbSet<SalesReturn> SalesReturns { get; set; }
        public virtual DbSet<StorageVoucher> StorageVouchers { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
    }
}
