//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUASCYCLAB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PackingList
    {
        public PackingList()
        {
            this.InventoryRecords = new HashSet<InventoryRecord>();
            this.InventoryRecords1 = new HashSet<InventoryRecord>();
            this.SalesCharts = new HashSet<SalesChart>();
            this.SalesRequestPaymentRecords = new HashSet<SalesRequestPaymentRecord>();
            this.SalesReturns = new HashSet<SalesReturn>();
        }
        [Key]
        [Display(Name = "出貨單編號")]
        public System.Guid PackingListID { get; set; }
        [Required]
        [Display(Name = "送貨日期")]
        public System.DateTime DeliveryDate { get; set; }
        [Required]
        [Display(Name = "送貨員工姓名")]
        public string Deliveryman { get; set; }
        [Required]
        [Display(Name = "倉管部處理員工姓名")]
        public string WarehouseStaff { get; set; }
        [Required]
        [Display(Name = "業務部處理員工姓名")]
        public string BusinessProcessEmployee { get; set; }
        [Display(Name = "備註")]
        public string Remark { get; set; }
        [Required]
        [Display(Name = "訂單編號之銷售人員")]
        public System.Guid SalesOrderID { get; set; }

        public virtual ICollection<InventoryRecord> InventoryRecords { get; set; }
        public virtual ICollection<InventoryRecord> InventoryRecords1 { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual ICollection<SalesChart> SalesCharts { get; set; }
        public virtual ICollection<SalesRequestPaymentRecord> SalesRequestPaymentRecords { get; set; }
        public virtual ICollection<SalesReturn> SalesReturns { get; set; }
    }
}
