//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUASCYCLAB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class ProductionOrder
    {
        public ProductionOrder()
        {
            this.InventoryReceipts = new HashSet<InventoryReceipt>();
            this.MaterialInventoryRecords = new HashSet<MaterialInventoryRecord>();
        }
        [Key]
        [Display(Name = "生產單編號")]
        public System.Guid ProductionOrderID { get; set; }
        [Display(Name = "開始生產日期")]
        public System.DateTime StartProductionDate { get; set; }
        [Display(Name = "結束期限")]
        public System.DateTime Closingdate { get; set; }
        [Display(Name = "生產商品名稱")]
        public string ProductionProductName { get; set; }
        [Display(Name = "生產商品規格")]
        public string ProductionProductSpecifications { get; set; }
        [Display(Name = "生產數量")]
        public string QuantityProduction { get; set; }
        [Display(Name = "生產總數量")]
        public string TotalQuantityProduction { get; set; }
        [Display(Name = "倉管部申請員工姓名")]
        public string CangguanApplyEmployee { get; set; }
        [Display(Name = "生產部處理員工姓名")]
        public string ProductionProcessingEmployee { get; set; }
        public string Remark { get; set; }
        public System.Guid BOMID { get; set; }

        public virtual BOMList BOMList { get; set; }
        public virtual ICollection<InventoryReceipt> InventoryReceipts { get; set; }
        public virtual ICollection<MaterialInventoryRecord> MaterialInventoryRecords { get; set; }
    }
}
