//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUASCYCLAB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Quotation
    {
        public Quotation()
        {
            this.SalesOrders = new HashSet<SalesOrder>();
        }
        [Key]
        [Display(Name = "報價單編號")]
        public System.Guid QuotationID { get; set; }
        [Display(Name = "業務部接單員工姓名")]
        public string BusinessOrdersEmployee { get; set; }
        [Display(Name = "報價日期")]
        public System.DateTime QuoteDate { get; set; }
        [Display(Name = "報價金額")]
        public string OfferAmount { get; set; }
        [Display(Name = "備註")]
        public string Remark { get; set; }
        [Display(Name = "詢價人")]
        public System.Guid InquiryID { get; set; }

        public virtual Inquiry Inquiry { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}
