//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUASCYCLAB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SalesInvoice_
    {
        public SalesInvoice_()
        {
            this.IncomeStatements = new HashSet<IncomeStatement>();
        }
        [Key]
        [Display(Name = "銷項發票編號")]
        public System.Guid SalesInvoiceID { get; set; }
        [Display(Name = "統一編號")]
        public string UniformID { get; set; }
        [Display(Name = "開票日期")]
        public System.DateTime InvoiceDate { get; set; }
        [Display(Name = "銷項稅費")]
        public string OutputTaxCharges { get; set; }
        [Display(Name = "會計部處理員工姓名")]
        public string AccountingDepartmentHandleEmployee { get; set; }
        [Display(Name = "付款人姓名")]
        public string PayName { get; set; }
        [Display(Name = "銷貨請款單編號")]
        public System.Guid SalesRequestPaymentID { get; set; }

        public virtual ICollection<IncomeStatement> IncomeStatements { get; set; }
        public virtual SalesRequestPaymentRecord SalesRequestPaymentRecord { get; set; }
    }
}
