//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUASCYCLAB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SalesRequestPaymentRecord
    {
        public SalesRequestPaymentRecord()
        {
            this.SalesInvoice_ = new HashSet<SalesInvoice_>();
            this.SalesRequestPayments = new HashSet<SalesRequestPayment>();
        }
        [Key]
        [Display(Name = "蕭貨請款單紀錄編號")]
        public System.Guid SalesRequestPaymentRecordID { get; set; }
        [Display(Name = "記錄日期")]
        public System.DateTime Date { get; set; }
        [Display(Name = "請款狀況")]
        public string Status { get; set; }
        [Display(Name = "備註")]
        public string Remark { get; set; }
        [Display(Name = "倉管部紀錄員工姓名")]
        public string AccountingDepartmentEmployee { get; set; }
        public System.Guid PackingListID { get; set; }

        public virtual PackingList PackingList { get; set; }
        public virtual ICollection<SalesInvoice_> SalesInvoice_ { get; set; }
        public virtual ICollection<SalesRequestPayment> SalesRequestPayments { get; set; }
    }
}
