//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUASCYCLAB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SalesOrder
    {
        public SalesOrder()
        {
            this.PackingLists = new HashSet<PackingList>();
        }
        [Key]
        [Display(Name = "訂單編號")]
        public System.Guid SalesOrderID { get; set; }
        [Display(Name = "訂購日期")]
        public System.DateTime OrderDate { get; set; }
        [Display(Name = "收件者姓名")]
        public string ToName { get; set; }
        [Display(Name = "收件地點")]
        public string RecipientPlace { get; set; }
        [Display(Name = "收件者連絡電話")]
        public string RecipientsPhone { get; set; }
        [Display(Name = "預期收件日期")]
        public System.DateTime ExpectedReceiptDate { get; set; }
        [Display(Name = "訂購數量")]
        public string Qty { get; set; }
        [Display(Name = "訂購總數量")]
        public string TotalQty { get; set; }
        [Display(Name = "訂購金額")]
        public string PurchaseAmount { get; set; }
        [Display(Name = "訂購總金額")]
        public string TotalOrderAmount { get; set; }
        [Display(Name = "備註")]
        public string Remark { get; set; }
        [Display(Name = "業務部處理員工姓名")]
        public string BusinessProcessEmployee { get; set; }
        [Display(Name = "倉管部處理員工姓名")]
        public string WarehouseDealingEmployee { get; set; }
        public System.Guid QuotationID { get; set; }
        public System.Guid CustomerID { get; set; }

        public virtual CustomerProfile CustomerProfile { get; set; }
        public virtual ICollection<PackingList> PackingLists { get; set; }
        public virtual Quotation Quotation { get; set; }
    }
}
