//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUASCYCLAB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SalesIncomeRecord
    {
        public SalesIncomeRecord()
        {
            this.IncomeStatements = new HashSet<IncomeStatement>();
        }
        [Key]
        [Display(Name = "銷貨入款單紀錄編號")]
        public System.Guid SalesIncomeRecordID { get; set; }
        [Display(Name = "紀錄日期")]
        public System.DateTime Date { get; set; }
        [Display(Name = "入款帳號")]
        public string AccountNumber { get; set; }
        [Display(Name = "備註")]
        public string Remark { get; set; }
        [Display(Name = "會計部紀錄員工姓名")]
        public string AccountingDepartmentEmployee { get; set; }
        public System.Guid SalesIncomeID { get; set; }

        public virtual ICollection<IncomeStatement> IncomeStatements { get; set; }
        public virtual SalesIncome SalesIncome { get; set; }
    }
}
