//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUASCYCLAB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SalesChart
    {
        [Key]
        [Display(Name = "銷貨排行榜編號")]
        public System.Guid SalesChartsID { get; set; }
        [Display(Name = "排行年度")]
        public string AnnualRanking { get; set; }
        [Display(Name = "熱門名次")]
        public string TopRanking { get; set; }
        [Display(Name = "冷門名次")]
        public string LessPopularRanking { get; set; }
        [Display(Name = "熱門商品名稱")]
        public string TopRankingName { get; set; }
        [Display(Name = "冷門商品名稱")]
        public string LessPopularRankingName { get; set; }
        [Display(Name = "熱門商品規格")]
        public string TopProductSpecifications { get; set; }
        [Display(Name = "冷門商品規格")]
        public string Less_popular_Product_Specifications { get; set; }
        [Display(Name = "出貨單")]
        public System.Guid PackingListID { get; set; }

        public virtual PackingList PackingList { get; set; }
    }
}
