//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kendo.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kendo.Mvc.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Add column on the left 的當地語系化字串。
        /// </summary>
        public static string Editor_AddColumnLeft {
            get {
                return ResourceManager.GetString("Editor_AddColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add column on the right 的當地語系化字串。
        /// </summary>
        public static string Editor_AddColumnRight {
            get {
                return ResourceManager.GetString("Editor_AddColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add row above 的當地語系化字串。
        /// </summary>
        public static string Editor_AddRowAbove {
            get {
                return ResourceManager.GetString("Editor_AddRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add row below 的當地語系化字串。
        /// </summary>
        public static string Editor_AddRowBelow {
            get {
                return ResourceManager.GetString("Editor_AddRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Background color 的當地語系化字串。
        /// </summary>
        public static string Editor_BackColor {
            get {
                return ResourceManager.GetString("Editor_BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bold 的當地語系化字串。
        /// </summary>
        public static string Editor_Bold {
            get {
                return ResourceManager.GetString("Editor_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert hyperlink 的當地語系化字串。
        /// </summary>
        public static string Editor_CreateLink {
            get {
                return ResourceManager.GetString("Editor_CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create table 的當地語系化字串。
        /// </summary>
        public static string Editor_CreateTable {
            get {
                return ResourceManager.GetString("Editor_CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete column 的當地語系化字串。
        /// </summary>
        public static string Editor_DeleteColumn {
            get {
                return ResourceManager.GetString("Editor_DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete &quot;{0}&quot;? 的當地語系化字串。
        /// </summary>
        public static string Editor_DeleteFile {
            get {
                return ResourceManager.GetString("Editor_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete row 的當地語系化字串。
        /// </summary>
        public static string Editor_DeleteRow {
            get {
                return ResourceManager.GetString("Editor_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 or 的當地語系化字串。
        /// </summary>
        public static string Editor_DialogButtonSeparator {
            get {
                return ResourceManager.GetString("Editor_DialogButtonSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Editor_DialogCancel {
            get {
                return ResourceManager.GetString("Editor_DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert 的當地語系化字串。
        /// </summary>
        public static string Editor_DialogInsert {
            get {
                return ResourceManager.GetString("Editor_DialogInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update 的當地語系化字串。
        /// </summary>
        public static string Editor_DialogUpdate {
            get {
                return ResourceManager.GetString("Editor_DialogUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A directory with this name was not found. 的當地語系化字串。
        /// </summary>
        public static string Editor_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Editor_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 drop files here to upload 的當地語系化字串。
        /// </summary>
        public static string Editor_DropFilesHere {
            get {
                return ResourceManager.GetString("Editor_DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Empty Folder 的當地語系化字串。
        /// </summary>
        public static string Editor_EmptyFolder {
            get {
                return ResourceManager.GetString("Editor_EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select font family 的當地語系化字串。
        /// </summary>
        public static string Editor_FontName {
            get {
                return ResourceManager.GetString("Editor_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (inherited font) 的當地語系化字串。
        /// </summary>
        public static string Editor_FontNameInherit {
            get {
                return ResourceManager.GetString("Editor_FontNameInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select font size 的當地語系化字串。
        /// </summary>
        public static string Editor_FontSize {
            get {
                return ResourceManager.GetString("Editor_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (inherited size) 的當地語系化字串。
        /// </summary>
        public static string Editor_FontSizeInherit {
            get {
                return ResourceManager.GetString("Editor_FontSizeInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Color 的當地語系化字串。
        /// </summary>
        public static string Editor_ForeColor {
            get {
                return ResourceManager.GetString("Editor_ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Format 的當地語系化字串。
        /// </summary>
        public static string Editor_FormatBlock {
            get {
                return ResourceManager.GetString("Editor_FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Format 的當地語系化字串。
        /// </summary>
        public static string Editor_Formatting {
            get {
                return ResourceManager.GetString("Editor_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Alternate text 的當地語系化字串。
        /// </summary>
        public static string Editor_ImageAltText {
            get {
                return ResourceManager.GetString("Editor_ImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Web address 的當地語系化字串。
        /// </summary>
        public static string Editor_ImageWebAddress {
            get {
                return ResourceManager.GetString("Editor_ImageWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Indent 的當地語系化字串。
        /// </summary>
        public static string Editor_Indent {
            get {
                return ResourceManager.GetString("Editor_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert file 的當地語系化字串。
        /// </summary>
        public static string Editor_InsertFile {
            get {
                return ResourceManager.GetString("Editor_InsertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert HTML 的當地語系化字串。
        /// </summary>
        public static string Editor_InsertHtml {
            get {
                return ResourceManager.GetString("Editor_InsertHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert image 的當地語系化字串。
        /// </summary>
        public static string Editor_InsertImage {
            get {
                return ResourceManager.GetString("Editor_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert ordered list 的當地語系化字串。
        /// </summary>
        public static string Editor_InsertOrderedList {
            get {
                return ResourceManager.GetString("Editor_InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert unordered list 的當地語系化字串。
        /// </summary>
        public static string Editor_InsertUnorderedList {
            get {
                return ResourceManager.GetString("Editor_InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The selected file &quot;{0}&quot; is not valid. Supported file types are {1}. 的當地語系化字串。
        /// </summary>
        public static string Editor_InvalidFileType {
            get {
                return ResourceManager.GetString("Editor_InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Italic 的當地語系化字串。
        /// </summary>
        public static string Editor_Italic {
            get {
                return ResourceManager.GetString("Editor_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Center text 的當地語系化字串。
        /// </summary>
        public static string Editor_JustifyCenter {
            get {
                return ResourceManager.GetString("Editor_JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Justify 的當地語系化字串。
        /// </summary>
        public static string Editor_JustifyFull {
            get {
                return ResourceManager.GetString("Editor_JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Align text left 的當地語系化字串。
        /// </summary>
        public static string Editor_JustifyLeft {
            get {
                return ResourceManager.GetString("Editor_JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Align text right 的當地語系化字串。
        /// </summary>
        public static string Editor_JustifyRight {
            get {
                return ResourceManager.GetString("Editor_JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open link in new window 的當地語系化字串。
        /// </summary>
        public static string Editor_LinkOpenInNewWindow {
            get {
                return ResourceManager.GetString("Editor_LinkOpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Text 的當地語系化字串。
        /// </summary>
        public static string Editor_LinkText {
            get {
                return ResourceManager.GetString("Editor_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ToolTip 的當地語系化字串。
        /// </summary>
        public static string Editor_LinkToolTip {
            get {
                return ResourceManager.GetString("Editor_LinkToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Web address 的當地語系化字串。
        /// </summary>
        public static string Editor_LinkWebAddress {
            get {
                return ResourceManager.GetString("Editor_LinkWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Arrange by: 的當地語系化字串。
        /// </summary>
        public static string Editor_OrderBy {
            get {
                return ResourceManager.GetString("Editor_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string Editor_OrderByName {
            get {
                return ResourceManager.GetString("Editor_OrderByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Size 的當地語系化字串。
        /// </summary>
        public static string Editor_OrderBySize {
            get {
                return ResourceManager.GetString("Editor_OrderBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Outdent 的當地語系化字串。
        /// </summary>
        public static string Editor_Outdent {
            get {
                return ResourceManager.GetString("Editor_Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &apos;A file with name &quot;{0}&quot; already exists in the current directory. Do you want to overwrite it? 的當地語系化字串。
        /// </summary>
        public static string Editor_OverwriteFile {
            get {
                return ResourceManager.GetString("Editor_OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search 的當地語系化字串。
        /// </summary>
        public static string Editor_Search {
            get {
                return ResourceManager.GetString("Editor_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Strikethrough 的當地語系化字串。
        /// </summary>
        public static string Editor_Strikethrough {
            get {
                return ResourceManager.GetString("Editor_Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Styles 的當地語系化字串。
        /// </summary>
        public static string Editor_Styles {
            get {
                return ResourceManager.GetString("Editor_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Subscript 的當地語系化字串。
        /// </summary>
        public static string Editor_Subscript {
            get {
                return ResourceManager.GetString("Editor_Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Superscript 的當地語系化字串。
        /// </summary>
        public static string Editor_Superscript {
            get {
                return ResourceManager.GetString("Editor_Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Underline 的當地語系化字串。
        /// </summary>
        public static string Editor_Underline {
            get {
                return ResourceManager.GetString("Editor_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remove hyperlink 的當地語系化字串。
        /// </summary>
        public static string Editor_Unlink {
            get {
                return ResourceManager.GetString("Editor_Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload 的當地語系化字串。
        /// </summary>
        public static string Editor_UploadFile {
            get {
                return ResourceManager.GetString("Editor_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 View HTML 的當地語系化字串。
        /// </summary>
        public static string Editor_ViewHtml {
            get {
                return ResourceManager.GetString("Editor_ViewHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 And 的當地語系化字串。
        /// </summary>
        public static string Filter_And {
            get {
                return ResourceManager.GetString("Filter_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Filter_Cancel {
            get {
                return ResourceManager.GetString("Filter_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear 的當地語系化字串。
        /// </summary>
        public static string Filter_Clear {
            get {
                return ResourceManager.GetString("Filter_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is equal to 的當地語系化字串。
        /// </summary>
        public static string Filter_DateIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is after 的當地語系化字串。
        /// </summary>
        public static string Filter_DateIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is after or equal to 的當地語系化字串。
        /// </summary>
        public static string Filter_DateIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is before 的當地語系化字串。
        /// </summary>
        public static string Filter_DateIsLessThan {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is before or equal to 的當地語系化字串。
        /// </summary>
        public static string Filter_DateIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is not equal to 的當地語系化字串。
        /// </summary>
        public static string Filter_DateIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is equal to 的當地語系化字串。
        /// </summary>
        public static string Filter_EnumIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is not equal to 的當地語系化字串。
        /// </summary>
        public static string Filter_EnumIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Filter 的當地語系化字串。
        /// </summary>
        public static string Filter_Filter {
            get {
                return ResourceManager.GetString("Filter_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Filter_Info {
            get {
                return ResourceManager.GetString("Filter_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 is false 的當地語系化字串。
        /// </summary>
        public static string Filter_IsFalse {
            get {
                return ResourceManager.GetString("Filter_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 is true 的當地語系化字串。
        /// </summary>
        public static string Filter_IsTrue {
            get {
                return ResourceManager.GetString("Filter_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is equal to 的當地語系化字串。
        /// </summary>
        public static string Filter_NumberIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is greater than 的當地語系化字串。
        /// </summary>
        public static string Filter_NumberIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is greater than or equal to 的當地語系化字串。
        /// </summary>
        public static string Filter_NumberIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is less than 的當地語系化字串。
        /// </summary>
        public static string Filter_NumberIsLessThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is less than or equal to 的當地語系化字串。
        /// </summary>
        public static string Filter_NumberIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is not equal to 的當地語系化字串。
        /// </summary>
        public static string Filter_NumberIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operator 的當地語系化字串。
        /// </summary>
        public static string Filter_Operator {
            get {
                return ResourceManager.GetString("Filter_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Or 的當地語系化字串。
        /// </summary>
        public static string Filter_Or {
            get {
                return ResourceManager.GetString("Filter_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Filter_SelectValue {
            get {
                return ResourceManager.GetString("Filter_SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contains 的當地語系化字串。
        /// </summary>
        public static string Filter_StringContains {
            get {
                return ResourceManager.GetString("Filter_StringContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Does not contain 的當地語系化字串。
        /// </summary>
        public static string Filter_StringDoesNotContain {
            get {
                return ResourceManager.GetString("Filter_StringDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ends with 的當地語系化字串。
        /// </summary>
        public static string Filter_StringEndsWith {
            get {
                return ResourceManager.GetString("Filter_StringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is equal to 的當地語系化字串。
        /// </summary>
        public static string Filter_StringIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is not equal to 的當地語系化字串。
        /// </summary>
        public static string Filter_StringIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Starts with 的當地語系化字串。
        /// </summary>
        public static string Filter_StringStartsWith {
            get {
                return ResourceManager.GetString("Filter_StringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Value 的當地語系化字串。
        /// </summary>
        public static string Filter_Value {
            get {
                return ResourceManager.GetString("Filter_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Grid_Cancel {
            get {
                return ResourceManager.GetString("Grid_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel changes 的當地語系化字串。
        /// </summary>
        public static string Grid_CancelChanges {
            get {
                return ResourceManager.GetString("Grid_CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Grid_CancelDelete {
            get {
                return ResourceManager.GetString("Grid_CancelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Columns 的當地語系化字串。
        /// </summary>
        public static string Grid_Columns {
            get {
                return ResourceManager.GetString("Grid_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Column Settings 的當地語系化字串。
        /// </summary>
        public static string Grid_ColumnSettings {
            get {
                return ResourceManager.GetString("Grid_ColumnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete this record? 的當地語系化字串。
        /// </summary>
        public static string Grid_Confirmation {
            get {
                return ResourceManager.GetString("Grid_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        public static string Grid_ConfirmDelete {
            get {
                return ResourceManager.GetString("Grid_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add new record 的當地語系化字串。
        /// </summary>
        public static string Grid_Create {
            get {
                return ResourceManager.GetString("Grid_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        public static string Grid_Destroy {
            get {
                return ResourceManager.GetString("Grid_Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Done 的當地語系化字串。
        /// </summary>
        public static string Grid_Done {
            get {
                return ResourceManager.GetString("Grid_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Export to Excel 的當地語系化字串。
        /// </summary>
        public static string Grid_Excel {
            get {
                return ResourceManager.GetString("Grid_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lock 的當地語系化字串。
        /// </summary>
        public static string Grid_Lock {
            get {
                return ResourceManager.GetString("Grid_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Export to PDF 的當地語系化字串。
        /// </summary>
        public static string Grid_Pdf {
            get {
                return ResourceManager.GetString("Grid_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save changes 的當地語系化字串。
        /// </summary>
        public static string Grid_SaveChanges {
            get {
                return ResourceManager.GetString("Grid_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select 的當地語系化字串。
        /// </summary>
        public static string Grid_Select {
            get {
                return ResourceManager.GetString("Grid_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sort Ascending 的當地語系化字串。
        /// </summary>
        public static string Grid_SortAscending {
            get {
                return ResourceManager.GetString("Grid_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sort Descending 的當地語系化字串。
        /// </summary>
        public static string Grid_SortDescending {
            get {
                return ResourceManager.GetString("Grid_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unlock 的當地語系化字串。
        /// </summary>
        public static string Grid_Unlock {
            get {
                return ResourceManager.GetString("Grid_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update 的當地語系化字串。
        /// </summary>
        public static string Grid_Update {
            get {
                return ResourceManager.GetString("Grid_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Drag a column header and drop it here to group by that column 的當地語系化字串。
        /// </summary>
        public static string Group_Empty {
            get {
                return ResourceManager.GetString("Group_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} - {1} of {2} items 的當地語系化字串。
        /// </summary>
        public static string Pager_Display {
            get {
                return ResourceManager.GetString("Pager_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No items to display 的當地語系化字串。
        /// </summary>
        public static string Pager_Empty {
            get {
                return ResourceManager.GetString("Pager_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go to the first page 的當地語系化字串。
        /// </summary>
        public static string Pager_First {
            get {
                return ResourceManager.GetString("Pager_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 items per page 的當地語系化字串。
        /// </summary>
        public static string Pager_ItemsPerPage {
            get {
                return ResourceManager.GetString("Pager_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go to the last page 的當地語系化字串。
        /// </summary>
        public static string Pager_Last {
            get {
                return ResourceManager.GetString("Pager_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More pages 的當地語系化字串。
        /// </summary>
        public static string Pager_MorePages {
            get {
                return ResourceManager.GetString("Pager_MorePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go to the next page 的當地語系化字串。
        /// </summary>
        public static string Pager_Next {
            get {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 of {0} 的當地語系化字串。
        /// </summary>
        public static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Page 的當地語系化字串。
        /// </summary>
        public static string Pager_Page {
            get {
                return ResourceManager.GetString("Pager_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go to the previous page 的當地語系化字串。
        /// </summary>
        public static string Pager_Previous {
            get {
                return ResourceManager.GetString("Pager_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refresh 的當地語系化字串。
        /// </summary>
        public static string Pager_Refresh {
            get {
                return ResourceManager.GetString("Pager_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Drop Column Fields Here 的當地語系化字串。
        /// </summary>
        public static string PivotConfigurator_Columns {
            get {
                return ResourceManager.GetString("PivotConfigurator_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Columns 的當地語系化字串。
        /// </summary>
        public static string PivotConfigurator_ColumnsLabel {
            get {
                return ResourceManager.GetString("PivotConfigurator_ColumnsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fields 的當地語系化字串。
        /// </summary>
        public static string PivotConfigurator_FieldsLabel {
            get {
                return ResourceManager.GetString("PivotConfigurator_FieldsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Drop Data Fields Here 的當地語系化字串。
        /// </summary>
        public static string PivotConfigurator_Measures {
            get {
                return ResourceManager.GetString("PivotConfigurator_Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Measures 的當地語系化字串。
        /// </summary>
        public static string PivotConfigurator_MeasuresLabel {
            get {
                return ResourceManager.GetString("PivotConfigurator_MeasuresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Drop Rows Fields Here 的當地語系化字串。
        /// </summary>
        public static string PivotConfigurator_Rows {
            get {
                return ResourceManager.GetString("PivotConfigurator_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rows 的當地語系化字串。
        /// </summary>
        public static string PivotConfigurator_RowsLabel {
            get {
                return ResourceManager.GetString("PivotConfigurator_RowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string PivotFieldMenu_Cancel {
            get {
                return ResourceManager.GetString("PivotFieldMenu_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear 的當地語系化字串。
        /// </summary>
        public static string PivotFieldMenu_Clear {
            get {
                return ResourceManager.GetString("PivotFieldMenu_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Filter 的當地語系化字串。
        /// </summary>
        public static string PivotFieldMenu_Filter {
            get {
                return ResourceManager.GetString("PivotFieldMenu_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fields Filter 的當地語系化字串。
        /// </summary>
        public static string PivotFieldMenu_FilterFields {
            get {
                return ResourceManager.GetString("PivotFieldMenu_FilterFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Include Fields... 的當地語系化字串。
        /// </summary>
        public static string PivotFieldMenu_Include {
            get {
                return ResourceManager.GetString("PivotFieldMenu_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show items with value that: 的當地語系化字串。
        /// </summary>
        public static string PivotFieldMenu_Info {
            get {
                return ResourceManager.GetString("PivotFieldMenu_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ok 的當地語系化字串。
        /// </summary>
        public static string PivotFieldMenu_Ok {
            get {
                return ResourceManager.GetString("PivotFieldMenu_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fields to include 的當地語系化字串。
        /// </summary>
        public static string PivotFieldMenu_Title {
            get {
                return ResourceManager.GetString("PivotFieldMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 all day 的當地語系化字串。
        /// </summary>
        public static string Scheduler_AllDay {
            get {
                return ResourceManager.GetString("Scheduler_AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Cancel {
            get {
                return ResourceManager.GetString("Scheduler_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete this event? 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Confirmation {
            get {
                return ResourceManager.GetString("Scheduler_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Date 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Date {
            get {
                return ResourceManager.GetString("Scheduler_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All events 的當地語系化字串。
        /// </summary>
        public static string Scheduler_DefaultRowText {
            get {
                return ResourceManager.GetString("Scheduler_DefaultRowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete event 的當地語系化字串。
        /// </summary>
        public static string Scheduler_DeleteWindowTitle {
            get {
                return ResourceManager.GetString("Scheduler_DeleteWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Destroy {
            get {
                return ResourceManager.GetString("Scheduler_Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All day event 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_AllDayEvent {
            get {
                return ResourceManager.GetString("Scheduler_Editor_AllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Description 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_Description {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Event 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_EditorTitle {
            get {
                return ResourceManager.GetString("Scheduler_Editor_EditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_End {
            get {
                return ResourceManager.GetString("Scheduler_Editor_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End timezone 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_EndTimezone {
            get {
                return ResourceManager.GetString("Scheduler_Editor_EndTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No timezone 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_NoTimezone {
            get {
                return ResourceManager.GetString("Scheduler_Editor_NoTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_Repeat {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use separate start and end time zones 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_SeparateTimezones {
            get {
                return ResourceManager.GetString("Scheduler_Editor_SeparateTimezones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_Start {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start timezone 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_StartTimezone {
            get {
                return ResourceManager.GetString("Scheduler_Editor_StartTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似   的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_Timezone {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Time zone 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_TimezoneEditorButton {
            get {
                return ResourceManager.GetString("Scheduler_Editor_TimezoneEditorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timezones 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_TimezoneEditorTitle {
            get {
                return ResourceManager.GetString("Scheduler_Editor_TimezoneEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Title 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Editor_Title {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Event 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Event {
            get {
                return ResourceManager.GetString("Scheduler_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to delete only this event occurrence or the whole series? 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_DeleteRecurring {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete current occurrence 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_DeleteWindowOccurrence {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteWindowOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete the series 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_DeleteWindowSeries {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteWindowSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete Recurring Item 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_DeleteWindowTitle {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  days(s) 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Daily_Interval {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Daily_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat every:  的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Daily_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Daily_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 After  的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_After {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End: 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_Label {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ends 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_MobileLabel {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_MobileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Never 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_Never {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  occurrence(s) 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_Occurrence {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_Occurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 On  的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_On {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Daily 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Daily {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Monthly 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Monthly {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Never 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Never {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Weekly 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Weekly {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Yearly 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Yearly {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Day  的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_Day {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  month(s) 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_Interval {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat every:  的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat on:  的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_RepeatOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 first 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_First {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 fourth 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Fourth {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 last 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Last {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 second 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Second {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 third 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Third {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 day 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekdays_Day {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekdays_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 weekday 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekdays_Weekday {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekdays_Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 weekend day 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekdays_Weekend {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekdays_Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  week(s) 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekly_Interval {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekly_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat every:  的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekly_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekly_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat on:  的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekly_RepeatOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekly_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  year(s) 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_Interval {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  of  的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_Of {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat every:  的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat on:  的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_RepeatOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to edit only this event occurrence or the whole series? 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_EditRecurring {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit current occurrence 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_EditWindowOccurrence {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditWindowOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit the series 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_EditWindowSeries {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditWindowSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit Recurring Item 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Recurrence_EditWindowTitle {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Save {
            get {
                return ResourceManager.GetString("Scheduler_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show full day 的當地語系化字串。
        /// </summary>
        public static string Scheduler_ShowFullDay {
            get {
                return ResourceManager.GetString("Scheduler_ShowFullDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show business hours 的當地語系化字串。
        /// </summary>
        public static string Scheduler_ShowWorkDay {
            get {
                return ResourceManager.GetString("Scheduler_ShowWorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Time 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Time {
            get {
                return ResourceManager.GetString("Scheduler_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Today 的當地語系化字串。
        /// </summary>
        public static string Scheduler_Today {
            get {
                return ResourceManager.GetString("Scheduler_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Agenda 的當地語系化字串。
        /// </summary>
        public static string Scheduler_View_Agenda {
            get {
                return ResourceManager.GetString("Scheduler_View_Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Day 的當地語系化字串。
        /// </summary>
        public static string Scheduler_View_Day {
            get {
                return ResourceManager.GetString("Scheduler_View_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Month 的當地語系化字串。
        /// </summary>
        public static string Scheduler_View_Month {
            get {
                return ResourceManager.GetString("Scheduler_View_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Week 的當地語系化字串。
        /// </summary>
        public static string Scheduler_View_Week {
            get {
                return ResourceManager.GetString("Scheduler_View_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Work Week 的當地語系化字串。
        /// </summary>
        public static string Scheduler_View_WorkWeek {
            get {
                return ResourceManager.GetString("Scheduler_View_WorkWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Upload_Cancel {
            get {
                return ResourceManager.GetString("Upload_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 drop files here to upload 的當地語系化字串。
        /// </summary>
        public static string Upload_DropFilesHere {
            get {
                return ResourceManager.GetString("Upload_DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Done 的當地語系化字串。
        /// </summary>
        public static string Upload_HeaderStatusUploaded {
            get {
                return ResourceManager.GetString("Upload_HeaderStatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Uploading... 的當地語系化字串。
        /// </summary>
        public static string Upload_HeaderStatusUploading {
            get {
                return ResourceManager.GetString("Upload_HeaderStatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remove 的當地語系化字串。
        /// </summary>
        public static string Upload_Remove {
            get {
                return ResourceManager.GetString("Upload_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Retry 的當地語系化字串。
        /// </summary>
        public static string Upload_Retry {
            get {
                return ResourceManager.GetString("Upload_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select... 的當地語系化字串。
        /// </summary>
        public static string Upload_Select {
            get {
                return ResourceManager.GetString("Upload_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 failed 的當地語系化字串。
        /// </summary>
        public static string Upload_StatusFailed {
            get {
                return ResourceManager.GetString("Upload_StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 uploaded 的當地語系化字串。
        /// </summary>
        public static string Upload_StatusUploaded {
            get {
                return ResourceManager.GetString("Upload_StatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 uploading 的當地語系化字串。
        /// </summary>
        public static string Upload_StatusUploading {
            get {
                return ResourceManager.GetString("Upload_StatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload files 的當地語系化字串。
        /// </summary>
        public static string Upload_UploadSelectedFiles {
            get {
                return ResourceManager.GetString("Upload_UploadSelectedFiles", resourceCulture);
            }
        }
    }
}
